language: haskell

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

install:
  - CABAL_FLAGS="--enable-tests --enable-benchmarks --enable-library-coverage"
  - cabal update
  - cabal install happy 'JuicyPixels-3.2.7' -v2 || cat /home/travis/.cabal/logs/JuicyPixels-3.2.7.log

script:
  - cabal install --only-dependencies $CABAL_FLAGS
  - cabal configure $CABAL_FLAGS
  - cabal build --ghc-options=-Werror
  - cabal test
  - cabal check
